### ISSUE TITLE
Build failed on linux

### ISSUE THREAD

**Issue by ghost** [acsearle/backlight#2]
Building failed at ```cmake ..```:
```bash
CMake Error: The source directory "/home/miner34/Downloads/backlight-master" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by acsearle** [comment]
See README:

## Building on Linux
To build on Linux, use the CMakeLists in the `backlight/` folder:
```shell
cd backlight
mkdir build
cmake ..
make
```

**Comment by m4r35n357** [comment]
```
CMake Error: The source directory "/opt/Backlight/backlight" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

```
I first tried this quite a few years ago but couldn't get it to build on Linux, so moved on to other things, I'd love to see it in action finally! ;)

In the event, I ended up having to use the horrible Povray "macro" language to make these videos [https://www.youtube.com/playlist?list=PLvGnzGhIWTGR-O332xj0sToA0Yk1X7IuI](url).  I thought Backlight might be a better way, but never got to find out :(

**Comment by m4r35n357** [comment]
I found this from six years ago, don't even remember it! [https://github.com/acsearle/backlight/pull/1#issuecomment-314866322]

I now have an executable.  Suggest editing README:

```
cd backlight
mkdir build
cd build
cmake ..
make

```

**Comment by ghost** [comment]
Yes! it built correctly!

**Comment by m4r35n357** [comment]
My memory is obviously failing me ;)  Just working through examples, the texture one segfaults, but the others produce output, not sure yet if it is correct.

**Comment by acsearle** [comment]
Flattered by the burst of interest.  I wrote this 25 years ago as a first year physics student so it's a miracle that anything _doesn't_ segfault.  The scene description language is based on povray and is surely worse for general purpose use.  I don't know if there are any other tools out there for relativistically accurate rendering these days.

**Comment by m4r35n357** [comment]
Flattered by your response ;)  I looked into updating my YT video stuff a while back but couldn't understand my own POVRay code!  I am only an "amateur" coder, and those half-function half-macro things are horrible.  Your scene descriptions might yet be usable, but I certainly don't have the "chops" to alter the sources if I find problems.  I will probably spend a little while looking at these things anyway.  No time constraints ;)

**Comment by ghost** [comment]
> it's a miracle that anything _doesn't_ segfault.

Only the texture example never works, but the problem is that... the texture doesn't exist!
